# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/project_7/project_7/project_7.cache/wt [current_project]
set_property parent.project_path D:/project_7/project_7/project_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/project_7/project_7/project_7.srcs/sources_1/new/cordic.v
  D:/project_7/project_7/project_7.srcs/sources_1/new/seven_segment.v
  D:/project_7/project_7/project_7.srcs/sources_1/new/lav7_top.v
  D:/project_6/project_6/project_6.srcs/sources_1/new/clock_divider.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/project_7/project_7/project_7.srcs/constrs_1/new/lab7.xdc
set_property used_in_implementation false [get_files D:/project_7/project_7/project_7.srcs/constrs_1/new/lab7.xdc]


synth_design -top lab7_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab7_top.dcp

catch { report_utilization -file lab7_top_utilization_synth.rpt -pb lab7_top_utilization_synth.pb }
