# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/guan0138/Desktop/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/guan0138/Desktop/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/guan0138/Desktop/project_4/project_4.srcs/sources_1/new/led_segment.v
  C:/Users/guan0138/Desktop/project_4/project_4.srcs/sources_1/new/lfsr.v
  C:/Users/guan0138/Desktop/project_4/project_4.srcs/sources_1/new/clock_divider.v
  C:/Users/guan0138/Desktop/project_4/project_4.srcs/sources_1/new/lab4_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/guan0138/Desktop/project_4/project_4.srcs/constrs_1/new/lab4_top.xdc
set_property used_in_implementation false [get_files C:/Users/guan0138/Desktop/project_4/project_4.srcs/constrs_1/new/lab4_top.xdc]


synth_design -top lab4_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab4_top.dcp

catch { report_utilization -file lab4_top_utilization_synth.rpt -pb lab4_top_utilization_synth.pb }
